{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.moistmason",
    "module": "masons-library",
    "version": "0.1.0-DEV-5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-5.jar",
          "url": "masons-library-0.1.0-DEV-5.jar",
          "size": 30348,
          "sha512": "0c0ce4a1421a184fc843504bce67e0f3041b991f2ebc05995abf0842cf7fa49d962e4e87b88c826c95ea21ee1d46ae6a92998a35165a9aefdb380f86a7e32fa4",
          "sha256": "17abc6df3a905d7f506ae71a18a28e18a250d3b7b7a137bb6353a9a92164ff1d",
          "sha1": "c49e017260239b1c1fcc722da318c53dd7505f50",
          "md5": "692ca842e51560bab1e3eed7e831bfcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-5.jar",
          "url": "masons-library-0.1.0-DEV-5.jar",
          "size": 30348,
          "sha512": "0c0ce4a1421a184fc843504bce67e0f3041b991f2ebc05995abf0842cf7fa49d962e4e87b88c826c95ea21ee1d46ae6a92998a35165a9aefdb380f86a7e32fa4",
          "sha256": "17abc6df3a905d7f506ae71a18a28e18a250d3b7b7a137bb6353a9a92164ff1d",
          "sha1": "c49e017260239b1c1fcc722da318c53dd7505f50",
          "md5": "692ca842e51560bab1e3eed7e831bfcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-5-sources.jar",
          "url": "masons-library-0.1.0-DEV-5-sources.jar",
          "size": 15840,
          "sha512": "fdd85eb5afeb3b1569f09ac1b53fe1fd56865b35a2f00466989269aa6d35a0d263921fcd0ff8f4395a77a97e62a0ddb78f07899e5559e58b4c3130399ee8a747",
          "sha256": "dff5170a117147a24de3c4dfd73976f8735ad495120399db2be4f61db652df81",
          "sha1": "9d4f040d648d6b78f49b09b202160a273c0245e0",
          "md5": "befe0d29975bad2952b79c146b9197d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-5-javadoc.jar",
          "url": "masons-library-0.1.0-DEV-5-javadoc.jar",
          "size": 165129,
          "sha512": "d4f2cfa11faa59b51731c5e87ca20340ed31432be0503bf80e9fa2bbb661f2f4852c7e85395eed33701dc36984de374c9eee8180412bc11232bbd86caf054b1d",
          "sha256": "8c78099ca9feaa5d9e5ce546473463b0dc73c267475d8430d5ce096ba1dae17e",
          "sha1": "11ecff57c9a7f84828b6de4aa497f58984751dd6",
          "md5": "61ee567888a17cbc8d2f5b2865c5cb48"
        }
      ]
    }
  ]
}
