{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.moistmason",
    "module": "masons-library",
    "version": "0.1.0-DEV-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-2.jar",
          "url": "masons-library-0.1.0-DEV-2.jar",
          "size": 29513,
          "sha512": "57b71cd8e763695538b65d0ae8816d330702d1b66f8f1b2fc0b00aef15531022a82872397f7323612709dbe7a27996f6a06a078f66add827154cd70a5c706faa",
          "sha256": "42f7cd21af83bd1d9810b996d3691a500f9a6c0341e7b9d2db5748d9c29f1845",
          "sha1": "db513f56b6cd129f94cbf378dea21f47ac775283",
          "md5": "9455af97fa37676c7dceb879a57117da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-2.jar",
          "url": "masons-library-0.1.0-DEV-2.jar",
          "size": 29513,
          "sha512": "57b71cd8e763695538b65d0ae8816d330702d1b66f8f1b2fc0b00aef15531022a82872397f7323612709dbe7a27996f6a06a078f66add827154cd70a5c706faa",
          "sha256": "42f7cd21af83bd1d9810b996d3691a500f9a6c0341e7b9d2db5748d9c29f1845",
          "sha1": "db513f56b6cd129f94cbf378dea21f47ac775283",
          "md5": "9455af97fa37676c7dceb879a57117da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-2-sources.jar",
          "url": "masons-library-0.1.0-DEV-2-sources.jar",
          "size": 15317,
          "sha512": "129e9a4e9cfa7f5e571c6d7cd3d5fff274ce5fb32d0b3d39c1364840d5538815f73cd0b2b3ead0e1bd50aa99a374fd83479b6334aa94ad2847204b22b638ddd9",
          "sha256": "0112b0d3f59e07fcb038281c62b4ed5e3a98cffc23617d89a32ef598d58fd3ba",
          "sha1": "c86de522f81f15bfcc204fbb673b6254047d5c6b",
          "md5": "ac62668907b0401e1386a2382c602535"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "masons-library-0.1.0-DEV-2-javadoc.jar",
          "url": "masons-library-0.1.0-DEV-2-javadoc.jar",
          "size": 164221,
          "sha512": "9ec73556572cd01922f6cbc9d15b981025ba0b3541cec9446c1e3e6acab1968b4b8cc510b7d1c9fa9348443b780e1d4e5da97e829ac26e5ba11957a65f1a3ef9",
          "sha256": "5536876f249e5785f41f1cc1207e98a3d151c92135fb69d70c937417b5aaa695",
          "sha1": "d87e75fd0f417af3d43e212627fa569b0c35f73f",
          "md5": "b6fd5ed5124037af322dd0494f879665"
        }
      ]
    }
  ]
}
